package ui

import "strings"

// iconLegendGroups resolves symbols at render time, so explanations always use
// the active Nerd Font/ASCII vocabulary. Reused glyphs are described separately
// by context: for example, a bolt can mean a quick win or high priority.
func iconLegendGroups() []helpGroup {
	g := activeGlyphs
	return []helpGroup{
		{title: "ISSUE TYPES", rows: []helpRow{
			{g.TypeBug, "Bug"},
			{g.TypeFeature, "Feature"},
			{g.TypeTask, "Task"},
			{g.TypeEpic, "Epic"},
			{g.TypeChore, "Chore"},
			{g.TypeDefault, "Other issue type"},
		}},
		{title: "ISSUE STATUS", rows: []helpRow{
			{g.StOpen, "Open"},
			{g.StInProgress, "In progress"},
			{g.StBlocked, "Blocked"},
			{g.StClosed, "Closed"},
			{g.StDeferred, "Deferred"},
			{g.StPinned, "Pinned"},
			{g.StHooked, "Hooked"},
			{g.StReview, "Review"},
			{g.StUnknown, "Unknown status"},
		}},
		{title: "PRIORITY", rows: []helpRow{
			{"0 / " + g.PrCritical, "Critical"},
			{"1 / " + g.PrHigh, "High"},
			{"2 / " + g.PrMedium, "Medium"},
			{"3 / " + g.PrLow, "Low"},
			{"4 / " + g.PrBacklog, "Backlog"},
			{"↑ / ↓", "Priority hint: raise / lower"},
		}},
		{title: "ROW INDICATORS", rows: []helpRow{
			{g.Bolt, "Quick win (right edge)"},
			{g.Unlock + "N", "Unblocks N; high-impact blocker"},
			{"↪N", "Unblocks N issues"},
			{g.Overdue + "DUE", "Overdue due date"},
			{g.Stale, "Stale issue (no recent update)"},
			{"done/total", "Epic progress"},
			{g.Comment + "N", "Comments count"},
			{"@name", "Assignee"},
			{g.Pencil, "Author (when not assignee)"},
			{g.Tag, "Labels"},
			{"bars", "Graph importance sparkline"},
			{"age", "Time since last update"},
			{"italic age", "Edited since creation"},
			{"dim title", "Ephemeral issue / wisp"},
			{strings.Join(g.Spinner, ""), "Pending write / background work"},
			{"[REPO]", "Project namespace"},
		}},
		{title: "GATES AND HUMAN FLAGS", rows: []helpRow{
			{g.GateHuman, "Human gate (red); advisory (yellow)"},
			{g.Clock, "Timer gate / time travel"},
			{g.GateCI, "CI gate"},
			{g.GatePR, "PR gate"},
			{g.GateBead, "Bead gate"},
			{g.GatePause, "Other wait / paused gate"},
		}},
		{title: "TIME-TRAVEL DIFF", rows: []helpRow{
			{g.New, "New issue"},
			{g.Success, "Closed issue"},
			{"~", "Modified issue (not an age marker)"},
		}},
		{title: "FOOTER AND FILTERS", rows: []helpRow{
			{g.TriadReady, "Ready / unblocked"},
			{g.TriadInFlight, "In-flight / in progress"},
			{g.TriadBlocked, "Blocked by dependencies"},
			{g.FilterAll, "All issues filter"},
			{g.FilterOpen, "Open issues filter"},
			{g.FilterClosed, "Closed issues filter"},
			{g.FilterReady, "Ready issues filter"},
			{g.FilterBQL, "BQL query / search"},
			{g.FilterRecipe, "Recipe filter"},
			{g.Search, "Search"},
			{g.Sort, "Sort order"},
			{g.SortAsc, "Ascending / oldest first"},
			{g.SortDesc, "Descending / newest first"},
			{g.Tag, "Labels / label filter"},
			{g.Graph, "Graph analysis"},
			{g.RepoDrawer, "Project filter drawer"},
			{g.Workspace, "Workspace / multiple projects"},
			{g.Bell, "Unread events"},
			{g.Star, "Update available"},
			{g.Session, "Linked cass sessions"},
		}},
		{title: "DEPENDENCIES", rows: []helpRow{
			{g.DepRoot, "Root issue"},
			{g.DepBlocks, "Blocking dependency"},
			{g.DepRelated, "Related issues"},
			{g.DepChild, "Parent-child dependency"},
			{g.DepDiscovered, "Discovered-from dependency"},
		}},
		{title: "HISTORY EVENTS", rows: []helpRow{
			{g.EventCreated, "Created"},
			{g.EventClaimed, "Claimed"},
			{g.EventClosed, "Closed"},
			{g.EventReopened, "Reopened"},
			{g.EventModified, "Modified"},
			{"@", "Direct commit mention"},
			{"~", "Temporal commit correlation"},
			{"#", "File-based commit correlation"},
		}},
		{title: "HEALTH AND NOTIFICATIONS", rows: []helpRow{
			{g.Phase2Dot, "Phase 2 metrics computing"},
			{g.Success, "Success / confirmation"},
			{g.Cross, "Failure / background error"},
			{g.Warning, "Warning / stale snapshot"},
			{g.Info, "Information"},
			{"↻ recov", "Worker self-healed"},
			{g.DotReady, "Green: ready / healthy"},
			{g.DotWarn, "Yellow: warning"},
			{g.DotHigh, "Orange: high impact"},
			{g.DotBlocked, "Red: blocked / unhealthy"},
			{g.DotInfo, "Blue: information"},
			{g.DotClosed, "Neutral: closed"},
			{g.DotIdle, "Hollow: idle"},
		}},
		{title: "SECTION AND DETAIL ICONS", rows: []helpRow{
			{g.BarChart, "Metrics / statistics"},
			{g.Target, "Recommendations / targets"},
			{g.Bulb, "Insights / suggestions"},
			{g.Brain, "Analysis / reasoning"},
			{g.Microscope, "Investigation"},
			{g.Books, "Documentation / learning"},
			{g.Satellite, "Cross-project overview"},
			{g.Building, "Project / organization"},
			{g.Construction, "Work in progress"},
			{g.Knot, "Dependency complexity"},
			{g.Cycle, "Cycles / recurring work"},
			{g.Hourglass, "Waiting / duration"},
			{g.Wrench, "Maintenance / tools"},
			{g.Memo, "Notes / edits"},
			{g.Page, "Issue / document"},
			{g.Clipboard, "Plan / checklist"},
			{g.Pushpin, "Pinned"},
			{g.Hook, "Hooked"},
			{g.Broom, "Cleanup"},
			{g.Package, "Package / deliverable"},
			{g.Paperclip, "Attachment / session"},
			{g.Scroll, "Description / history"},
			{g.TestTube, "Tests / experiments"},
			{g.Snowflake, "Deferred / frozen"},
			{g.Coffee, "Low urgency"},
			{g.Sleep, "Inactive / backlog"},
			{g.Fire, "Critical / hot spot"},
			{g.Rocket, "Epic / launch"},
			{g.Link, "Related / capability link"},
			{g.NoEntry, "Blocked / unavailable"},
			{g.Question, "Unknown / help"},
			{g.User, "Person / assignee"},
			{g.Globe, "Global / cross-project scope"},
			{g.Refresh, "Refresh / reopen"},
			{g.BrailleFull + g.BrailleHalf + g.BrailleTrack, "Epic progress bar"},
		}},
		{title: "TYPOGRAPHY", rows: []helpRow{
			{g.Sep + " / " + g.SepBar, "Section separators"},
			{g.Bullet, "List bullet"},
			{g.Ellipsis, "Truncated text"},
			{g.Return, "Enter / return"},
		}},
	}
}
